-- phpMyAdmin SQL Dump
-- version 4.1.7
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Lug 20, 2016 alle 00:00
-- Versione del server: 5.6.29-log
-- PHP Version: 5.3.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `my_hypertim2016`
--

-- --------------------------------------------------------

--
-- Struttura della tabella `assdevice`
--

CREATE TABLE IF NOT EXISTS `assdevice` (
  `deviceid` int(10) NOT NULL,
  `assid` int(10) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dump dei dati per la tabella `assdevice`
--

INSERT INTO `assdevice` (`deviceid`, `assid`) VALUES
(16, 1),
(1, 8),
(13, 5),
(6, 6);

-- --------------------------------------------------------

--
-- Struttura della tabella `assistance`
--

CREATE TABLE IF NOT EXISTS `assistance` (
  `id` int(10) NOT NULL,
  `name` text COLLATE utf8_unicode_ci NOT NULL,
  `description` longtext COLLATE utf8_unicode_ci NOT NULL,
  `category` enum('line','cost','technical','smart') COLLATE utf8_unicode_ci NOT NULL,
  `service_type` text COLLATE utf8_unicode_ci NOT NULL,
  `faq` mediumtext COLLATE utf8_unicode_ci,
  `highlights` enum('yes','no') COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dump dei dati per la tabella `assistance`
--

INSERT INTO `assistance` (`id`, `name`, `description`, `category`, `service_type`, `faq`, `highlights`) VALUES
(1, 'Attivazione linea di casa', 'Richiedere l''attivazione di una linea telefonica di casa e'' molto semplice, puoi: richiederla online, chiamare il Servizio Clienti linea fissa 187 oppure recarti presso un negozio TIM. Verifica la modalita'' di attivazione consultando le varie offerte disponibili.<br><b>I dati necessari sono:</b><br>nome e cognome,<br>codice fiscale,<br>indirizzo dell''abitazione per cui richiedi la linea,<br>un recapito telefonico sul cellulare,<br>indirizzo e-mail.<br>Il nostro personale ti contattera'' quanto prima per concordare l''appuntamento per l''installazione dell''impianto telefonico.', 'line', 'Fisso', '<b>QUANTO COSTA?</b><br><br>Il contributo per l''attivazione di una linea tradizionale e'' pari a 97,60 euro (IVA inclusa), salvo eventuali promozioni in corso.', 'yes'),
(2, 'Passaggio da abbonamento a ricaricabile', '<b>Descrizione:</b><br>per passare la tua utenza TIM da abbonamento a servizio ricaricabile puoi compilare il modulo di ''Richiesta di migrazione da abbonamento a ricaricabile''.<br>Il modulo e'' disponibile in formato pdf nella sezione Moduli e puo'' essere scaricato direttamente dalla sottosezione ''clienti con abbonamento''.<br> Potrai inviare il modulo compilato con la richiesta di cessazione del contratto di abbonamento e la specificata volonta'' di passare verso servizio ricaricabile (indicando il profilo e l''eventuale opzione) e la modalita'' di rimborso ACI (assegno/accredito su linea ricaricabile), al numero di fax dedicato 800600119.<br>Puoi effettuare il passaggio scrivendoci o in alternativa presso un qualsiasi Negozio TIM.', 'line', 'Mobile', NULL, 'yes'),
(3, 'MyTIM Fisso - Gestione linea', '<b>MyTIM Fisso - gestione linea</b><br>Registrandoti al MyTIM Fisso o scaricando l''applicazione per smartphone e tablet avrai  a disposizione tutte le informazioni relative alla tua linea telefonica. Potrai visualizzare i servizi e le offerte attivi sulla tua linea telefonica, pagare le tue fatture e avere informazioni relative al traffico.', 'line', 'Online', '<b>Perche'' dovrei registrarmi al MyTIM Fisso o scaricare l''app MyTIM Fisso?</b><br><br>Innanzi tutto perche'' e'' semplice e veloce, poi perche'' hai la possibilita'' di gestire autonomamente la tua linea.<br>Compila il modulo di registrazione per accedere ai nostri servizi. La registrazione e'' completa e certificata se utilizzi un collegamento Telecom Italia associato al codice fiscale da registrare:<br>- se sei gia'' un cliente internet TIM accedere utilizzando username e password di Alice Mail.<br>- se effettui la registrazione fuori casa o da una linea non TIM, dovrai chiamare il numero gratuito 40 123(opzione 2).<br>- le credenziali di accesso dell''applicazione MyTIM Fisso per smartphone e tablet sono quelle con le quali ti sei registrato alla sezione MyTIM Fisso.', 'no'),
(4, 'Come entrare in TIM con la tua linea mobile', '<b>Descrizione:</b><br>Il servizio di portabilita'' (MNP, cioe'' Mobile Number Portability) ti consente di cambiare Operatore telefonico portando con te il tuo numero di telefonino. Potrai passare a TIM:<br>1. direttamente al telefono con un nostro operatore che ti fornira'' tutti i dettagli sulle nostre offerte. Chiedi il ricontatto di un nostro operatore, entra in TIM!<br>2. direttamente online, cliccando sul tasto ''Attiva'' dell''Offerta scelta. Per scoprire i vantaggi e le modalita'' consulta la Guida.<br>3. Presso un Negozio TIM portando con te un documento d''identita'' e la SIM del tuo attuale operatore.<br><br>Nel momento della richiesta di portabilita'' riceverai una TIM Card con una numerazione provvisoria, con la quale potrai parlare, inviare SMS e utilizzare tutti gli altri servizi TIM, usufruendo da subito della tua nuova offerta.<br>A portabilita'' completata (non prima di 2 giorni lavorativi dalla richiesta), in automatico, il tuo numero andra'' a sovrascrivere la numerazione "transitoria" presente sulla nuova SIM di TIM. La suddetta operazione determina la proroga della durata della TIM Card di 13 mesi, decorrenti dalla data in cui la portabilita'' e'' completata.<br>Ti ricordiamo che nel corso del tredicesimo mese il servizio funzionera'' solo per la ricezione delle chiamate e dei messaggi.<br>Ti ricordiamo infine che per sapere se un numero e'' TIM puoi:<br>- Comporre il numero 456 seguito dal numero di telefono per il quale si desidera l''informazione (esempio 4563XXabcdefg): una fonia ti dira'' se il numero corrisponde ad un cliente TIM o ad un altro operatore<br>- Inviare un SMS (gratuito) al 456 con la seguente sintassi: INFO 3XXabcdefg.', 'line', 'TIM Transfer Help', NULL, 'no'),
(5, 'Come leggere la fattura', 'La fattura della linea fissa e'' semplice e facile da leggere perche'' disegnata prendendo spunto dai suggerimenti dei clienti. La veste grafica, moderna e raffinata, utilizza un linguaggio sempre piu'' chiaro per l''esposizione delle voci di spesa, facilitando la lettura di tutte le informazioni di cui hai bisogno e garantendo maggiore trasparenza nei contenuti e negli importi.', 'cost', 'Fisso', '<b>Come leggo la fattura della linea fissa?</b><br><br>Nella prima pagina trovi:<br>- i dati principali dell''intestatario della linea di casa e della fattura.<br>- il riepilogo degli abbonamenti attivi.<br>- un box informativo con le proposte commerciali personalizzate relative a  offerte, prodotti, servizi.<br>- l''informazione sulla modalita'' di pagamento (bollettino, addebito su conto corrente o su carta di credito).<br>- lo stato dei pagamenti.<br>- una guida veloce che riporta, attraverso semplici icone, i riferimenti per entrare in contatto con TIM: App MyTIM Fisso per Smartphone e Tablet, sito www.tim.it (registrandoti alla sezione MyTIM Fisso), Social Network (Facebook, Youtube, Twitter, Google+), Servizio clienti 187, Negozi TIM.<br>Nella pagina del ''Dettaglio dei costi'' le voci sono riordinate secondo una logica piu'' vicina alle tue esigenze: prima trovi gli eventuali ''Importi Una Tantum'' cioe'' quelli straordinari da pagare una sola volta, poi gli ''Abbonamenti'' (canoni delle offerte/prodotti/servizi attivi), segue la descrizione ''Telefonate e contenuti'' (consumi di traffico, sms, contenuti digitali come video on demand, ebook, ecc) ed infine la voce ''Altri importi'' (spese di produzione e spedizione fatture, le rate dei prodotti, le indennita'' di ritardato pagamento, interessi legali e moratori, consegna elenchi telefonici).', 'yes'),
(6, 'Dettaglio delle chiamate per i clienti ricaricabili', '<b>Descrizione:</b><br>Il servizio "documentazione traffico" ti offre la possibilita'' di avere il dettaglio di ogni telefonata, connessione dati o altro evento effettuato dalla tua linea (*).<br>Per ogni evento viene fornita l''indicazione della data/ora di effettuazione, del costo, della tipologia, del numero chiamato e se si tratti di traffico voce o SMS (con le ultime tre cifre asteriscate - L. 171/98 "Tutela vita privata nelle telecomunicazioni"). La documentazione del traffico e'' sempre disponibile in MyTIM Mobile e consultabile fino a due mesi antecedenti la data di effettuazione del traffico se utilizzi una linea ricaricabile, in diversi formati facilmente consultabili ed archiviabili (esempio pdf). E'' comunque possibile richiedere l''invio di un tabulato cartaceo del traffico pregresso (equivalente al pdf gia'' disponibile in MyTIM Mobile), o l''invio di un tabulato del traffico pregresso in chiaro (deve essere in questo caso specificato), purche'' rientri nei periodi sopra indicati. In questo caso dovrai compilare ed inviare l''apposito modulo di "Richiesta Documentazione Traffico" che puoi scaricare in formato pdf dalla sezione Moduli, selezionando la sottosezione ricaricabile di riferimento.<br><br>(*) alcune tipologie di traffico, per cui non e'' previsto un costo, possono non essere documentate.', 'cost', 'Mobile', NULL, 'yes'),
(7, 'Il mio conto online', '<b>Cos''e'' "Il mio Conto Online":</b><br> E'' il servizio gratuito che ti permette di visualizzare la fattura della tua linea fissa direttamente online, prima ancora che sia recapitata a casa via posta. Utilizzando il servizio "Il mio Conto" puoi inoltre scegliere di non ricevere piu'' la tua fattura in versione cartacea, risparmiando cosi'' i relativi costi, se hai richiesto la domiciliazione su conto corrente bancario/postale dei pagamenti. <b>Come aderire a "Il mio Conto Online":</b><br>Aderire e'' molto semplice. Basta registrarsi qui ed in fase di registrazione ti verra'' chiesto di inserire il tuo codice fiscale ed il tuo indirizzo email (che diventera'' la tua username). Se lo desideri, una volta registrato e domiciliato il pagamento delle fatture, puoi selezionare l''opzione di eliminazione dell''invio cartaceo della fattura.<br><b>I vantaggi di "Il mio Conto Online":</b><br>puoi consultare online in qualsiasi momento le fatture degli ultimi 12 mesi con il relativo stato di pagamento e con la possibilita'' di visualizzarle in formato .pdf, di salvarle sul tuo PC, di inviarle alla tua casella e-mail, di avere chiarimenti sul significato delle singole voci in fattura; puoi inviare segnalazioni al Servizio Clienti linea fissa 187 (ad es. segnalazione di errato addebito del traffico, richiesta di abilitazione o cessazione di un servizio, ecc.); hai maggior tempo a tua disposizione per controllare la fattura oltre ad avere la certezza di riceverla sempre e di non smarrirla; hai a disposizione la documentazione integrale delle tue telefonate che potrai analizzare selezionandole per tipo di chiamata, offerta, data, numero chiamato, fascia oraria, durata e costo e puoi  analizzare l''andamento dei consumi degli ultimi 12 mesi in forma tabellare e grafica. Puoi inoltre scaricare i grafici in formato excel; puoi visualizzare il traffico in chiaro relativo alle ultime quattro fatture; ogni mese riceverai una notifica via e-mail e sms, se ci fornisci il tuo numero mobile, sulla disponibilita'' dell''ultima fattura emessa all''interno della sezione MyTIM Fisso.', 'cost', 'Online', NULL, 'yes'),
(8, 'Assistenza tecnica specializzata con SOSsmartphone', '<b>Descrizione:</b><br>SOSsmartphone e'' il servizio di TIM per tutti i clienti, Ricaricabili o con Abbonamento, che permette di ricevere un''assistenza tecnica specializzata e personalizzata per la gestione del proprio smartphone o tablet.<br>Grazie al servizio SOSsmartphone potrai parlare con un esperto che ti fornira'' tutta la consulenza e l''assistenza "premium" di cui necessiti e che soprattutto sara'' in grado di connettersi in remoto ed operare direttamente sul tuo dispositivo.<br>I servizi che potrai ricevere con SOSsmartphone sono:<br>- supporto per trasferimento dati in caso di cambio telefono: esempio trasferimento rubrica, foto, sms;<br>- consulenza nell''utilizzo delle funzioni avanzate dello smartphone;<br>- assistenza specialistica sulle configurazioni avanzate dello smartphone e integrazione nella tua rete domestica;<br>- gestione e sincronizzazione dei tuoi contenuti multimediali;<br>- supporto per garantire il massimo della sicurezza;<br>- conservazione e protezione dei tuoi dati;<br>- trasferimento di contenuti;<br>- aggiornamento del tuo smartphone;<br>- effettuazione check up.<br>Per richiedere il servizio SOSsmartphone potrai:<br>contattare il numero 0458214811 (chiamata a pagamento in base al proprio piano tariffario/offerta);<br>scaricare l''App SOS Smartphone da APP Store (per iOS) e Google Play (per Android) e richiedere l''intervento.<br>Il servizio SOSsmartphone prevede un costo ad intervento a partire da 3euro (IVA inclusa). L''importo sara'' addebitato in fattura se sei un cliente con Abbonamento mentre, sara'' scalato dal credito residuo se sei un cliente Ricaricabile. Dal 12 maggio inoltre il servizio SOSsmartphone e'' disponibile anche in abbonamento a 2euro/mese. In questo modo avrai l''assistenza di cui hai bisogno sempre disponibile e completa per un anno.<br>Ti ricordiamo che nell''area Assistenza del sito TIM.it sono a tua disposizione tutte le guide per le configurazioni di smartphone, tablet e chiavette che ti consentiranno, in completata autonomia, di configurare il tuo telefonino a tutti i servizi TIM.', 'technical', 'Smartphone', NULL, 'yes'),
(9, 'Cos''e'' TIMgames', '<b>Descrizione:</b><br>TIMgames e'' il servizio TIM edicato al gaming che consente a tutti i clienti di scaricare su tablet e smartphone i migliori giochi on demand e in abbonamento per il mondo mobile. Con TIMgames avrai a disposizione una library di oltre 1500 giochi, aggiornata ogni settimana con nuovi titoli e giochi in offerta presenti nell''area promozioni dello store. TIMgames e'' accessibile sia da App (scaricabile da Google Play) che da browser su www.timgames.it. L''utente puo'' scegliere la modalita'' di acquisto preferita tra on demand e abbonamento.<br>In particolare:<br>On demand: a partire da 0,49euro, acquistando e scaricando un gioco sul proprio telefonino; <br>In abbonamento: con I Love Games Promo, a soli 2euro a settimana si possono scaricare senza limiti tutti i giochi presenti su TIMgames. Il primo mese e'' in promozione a solo 1euro a settimana.', 'smart', 'TIMgames', NULL, 'yes'),
(10, 'Cos''e'' TIMmusic', '<b>Descrizione:</b><br>TIMmusic e'' la piattaforma di musica digitale di Telecomitalia dedicata a tutti i clienti che hanno uno smartphone/tablet TIM o una linea ADSL o Fibra residenziale Telecom Italia o una chiavetta Internet TIM.<br>Con TIMmusic puoi ascoltare milioni di brani in streaming senza limiti di tempo sul tuo smartphone e tablet o sul PC (clienti ADSL e Fibra Residenziale Telecom Italia o con chiavetta Internet TIM). Puoi  creare tue playlist personali o ascoltare quelle suggerite da dj e artisti famosi e condividere tutto sui principali social network. Il catalogo e'' sempre aggiornato con tutte le ultime uscite discografiche, spesso anche in anteprima esclusiva. E, se sei su mobile, non consumi GB perche'' il traffico dati per l''ascolto di musica e'' incluso nel costo dell''abbonamento.', 'smart', 'TIMmusic', NULL, 'no');

-- --------------------------------------------------------

--
-- Struttura della tabella `devices`
--

CREATE TABLE IF NOT EXISTS `devices` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `name` text COLLATE latin1_general_ci NOT NULL,
  `price` float NOT NULL,
  `range` enum('1','2','3','4','5','6') COLLATE latin1_general_ci NOT NULL,
  `description` longtext COLLATE latin1_general_ci,
  `category` enum('smartphones','tv','tablet','modem') COLLATE latin1_general_ci NOT NULL,
  `brand` text COLLATE latin1_general_ci NOT NULL,
  `os` enum('Android','Windows','iOS') COLLATE latin1_general_ci DEFAULT NULL,
  `img` text COLLATE latin1_general_ci NOT NULL,
  `promotion` enum('yes','no') COLLATE latin1_general_ci DEFAULT NULL,
  `technical` mediumtext COLLATE latin1_general_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=28 ;

--
-- Dump dei dati per la tabella `devices`
--

INSERT INTO `devices` (`id`, `name`, `price`, `range`, `description`, `category`, `brand`, `os`, `img`, `promotion`, `technical`) VALUES
(1, 'Samsung Galaxy S7 Edge', 829.99, '6', 'Caratteristiche:<br>\nSistema Operativo Android 6.0<br>\nDisplay 5.5”<br>\nProcessore OctaCore (QuadCore 2.3 Ghz + QuadCore 1.6 Ghz)<br>', 'smartphones', 'Samsung', 'Android', './Immagini_Progetto/SamsungS7edge.png', 'no', 'Specifiche tecniche<br><br>\nSistema Operativo Android 6.0<br>\nDisplay 5.5”<br>\nProcessore OctaCore (QuadCore 2.3 Ghz + QuadCore 1.6 Ghz)<br><br>\nTecnologia<br>\n4G cat.9/HSDPA42UMTS/EDGE/GPRS Frequenze 850/900/1800/1900/2100<br><br>\nConnettivita<br>\nWi-Fi - Bluetooth - Micro USB - NFC<br><br>\nGPS Integrato<br>\nDisplay 5.5” 16 Milioni colori Touch<br><br>\nFotocamera 12 Mpixel/Flash<br>\nMemoria Interna 32GB<br>\nProcessore OctaCore: (QuadCore 2.3 Ghz+QuadCore 1.6 Ghz)<br><br>\nFormato SIM: Nano<br><br>\nVideo: Video Recorder&Playback<br>\nMusica: MP3 Player<br>\nIn dotazione:<br>\n- Caricabatteria<br>- Cavo Dati MicroUSB<br>- Auricolare stereo<br>- Guida di riferimento rapido<br><br>\nDimensioni: 150,9x72,6x7,7 mm<br>\nPeso: 157 gr.<br><br>\nAutonomia(*): Stand-by fino a TBD ore - Conversazione fino a TBD min<br><br>\nNote<br>\n* Le prestazioni delle batterie dipendono da vari fattori tra cui la vicinanza delle antenne, lo stato delle batterie, la posizione geografica e il tipo di rete utilizzata.'),
(2, 'Samsung Galaxy A5 (2016)', 429.99, '5', 'Descrizione:<br>\n4GPLUS<br>\nSistema Operativo Android 5.1.1<br>\nDisplay Full HD SuperAMOLED 5.2<br>\nProcessore Octa-Core 1.6 GHz<br>', 'smartphones', 'Samsung', 'Android', './Immagini_Progetto/galaxy_a5_2016_blocchetto.png', 'no', 'Specifiche tecniche\n<br><br>\nDimensioni\n<br>145 g / 144.7 x 70.8 x 7.25 mm\n<br><br>\nBatteria\n<br>- Capacità: 2900 mAh\n<br>- Autonomia: TBD\n<br><br>\nConnettivita\n<br>- USB 2.0 / Bluetooth 4.1 Low Energy \n<br>- 802.11 a/b/g/n 2.4+5GHz, HT40\n<br>- A-GPS + GLONASS\n<br>- Router Wi-Fi / Wi-Fi Direct\n<br>- NFC / Android Beam\n<br>- Connettore auricolare da 3,5 mm \n<br>- Supporto nanoSIM\n<br>- USB OTG\n<br><br>\nFotocamera\n<br>- 13 Mpx AF con FlashLED, Zoom digitale 4x, OIS , F1.9 (fotocamera posteriore)\n<br>- 5 Mpx, F1.9 (fotocamera anteriore)\n<br>- Modalità Pro, Autoscatto, Selfie panoramico, Panoramica, Scatto multiplo, HDR, Notte, Modalità aggiuntive scaricabili\n<br>- Foto: 4128x3096, 4128x2322, 3096x3096, 3264x2448, 3264x1836, 2048x1152\n<br>- Registrazione Video: 1920x1080, 1280x720, 640x480\n<br><br>\nDisplay\n<br>- Touchscreen Full HD SuperAMOLED 5.2’’ \n<br>- 1920 x 1080\n<br><br>\nMemoria\n<br>- 16 GB interna* (espandibile fino a 128 GB)\n<br>- 2 GB (RAM)'),
(3, 'LG G5', 699.99, '5', 'Caratteristiche:<br>\nSistema Operativo Android 6.0<br>\nDisplay 5.3”<br>\nProcessore Snapdragon™ 820 QuadCore 2.15 GHz - 4G LTE<br>', 'smartphones', 'LG', 'Android', './Immagini_Progetto/lg-g5-titan-blocchetto.png', 'no', 'Specifiche tecniche<br>\nSistema Operativo Android 6.0\n<br>Display 5.3”\n<br>Processore Snapdragon™ 820 <br>QuadCore 2.15 GHz - 4G LTE\n<br>Tecnologia\n4G cat.6/HSDPA42/UMTS/EDGE/GPRS Frequenze 850/900/1800/1900/2100<br>\n<br>Connettivita\nWi-Fi - Bluetooth – Infrarosso - USB tipo C – NFC<br>\nGPS\nIntegrato<br>\nDisplay\n5.3” 16 Milioni colori Touch<br>\nFotocamera\n2 Fotocamere Posteriori da 16 Mpxl con flash e Fotocamera frontale 8 Mpx<br>\nMemoria Interna\n32GB\nSlot Memory Card Micro SD fino a 2TB<br>\nProcessore\nProcessore Snapdragon™ 820 QuadCore 2.15 GHz - 4G LTE<br>\nFormato SIM\nNano<br>\nVideo\nVideo Recorder&Playback<br>\nMusica\nMP3 Player<br>\nIn dotazione\nCaricabatteria\nCavo dati USB tipo C\nAuricolare stereo\nManuale d’uso rapido<br>\nDimensioni\n149,4x73,9x7,3 mm<br>\nPeso\n159 gr.<br><br>\nAutonomia(*)\nStand-by fino a 100 ore - Conversazione fino a 240 min.<br>\nNote<br>\n* Le prestazioni delle batterie dipendono da vari fattori tra cui la vicinanza delle antenne, lo stato delle batterie, la posizione geografica e il tipo di rete utilizzata.'),
(4, 'Huawei P9', 599.99, '5', 'Caratteristiche:<br><br>\nSistema Operativo Android 6.0<br>\nDisplay 5.5”<br>\nProcessore OctaCore (QuadCore 2.3 Ghz + QuadCore 1.6 Ghz)', 'smartphones', 'Huawei', 'Android', './Immagini_Progetto/huawei-p9-grey-blocchetto.png', 'no', '<span class="description">PREMIUM. ELEGANT. STYLISH.</span><br><br>Huawei P9 presenta un design con linee dal forte impatto visivo, caratterizzate da spigoli tagliati a regola d''arte.Lo smartphone ha una struttura unibody in alluminio aerospaziale e vetro 2.5D di categoria superiore, ed &egrave; disponibile in due varianti cromatiche: Titanium Grey e Mystic Silver.<br><br><span class="description">DISPLAY LUMINOSO E DAI COLORI INTENSI</span><br><br>Con una resa cromatica del 96% il sensazionale display IPS Full HD da 5,2"  porta alla scoperta di un mondo ricco di colori intensi e ancora pi&ugrave; naturali<br><br><span class="description">UN INNOVATIVO SISTEMA CON DOPPIA FOTOCAMERA, UNA COLLABORAZIONE UNICA</span><br><br>La collaborazione tra Huawei e Leica ha dato vita a uno smartphone con doppia fotocamera. Il risultato: maggiore luminosit&agrave; e nitidezza per foto e video sensazionali.<br><br><span class="description">INNOVATIVO SISTEMA CON DOPPIA FOTOCAMERA</span><br><br>Huawei P9 &egrave; in grado di catturare immagini dai colori luminosi e garantire al contempo una resa in bianco e nero straordinaria; il tutto con lo stile senza tempo di Leica.La tecnologia con doppia fotocamera di Huawei P9 consente di catturare una maggiore quantit&agrave; di luce, combinando al meglio la qualit&agrave; del colore acquisito dal sensore RGB con i dettagli ottenuti dal sensore in bianco e nero. Il tutto per garantire il massimo risultato ad ogni scatto.<br><span class="technicaltitle">Tecnologia</span> <br>Abilitato tecnologia 4GPlus/4G/HSDPA 42/UMTS/EDGE/GPRS Frequenze 850/900/1800/1900MHz<br><br><span class="technicaltitle">Connettivita</span> <br>4G cat.6/HSDPA42/UMTS/EDGE/GPRS Frequenze 850/900/1800/1900/2100 Wi-Fi a/b/g/n/ac dual band 2,4/5GHz con Wi-Fi Direct Bluetooth 4.2, BLE USB Type-C, NFC<br><br><span class="technicaltitle">GPS</span> <br>GPS Integrato<br><br><span class="technicaltitle">Display</span> <br>Display IPS Full HD da 5.2"<br><br><span class="technicaltitle">Fotocamera</span> <br>Principale 12MP x 2, f/2.2 Leica BSI CMOS Flash dual-tone Frontale 8MP, f/2.4<br><br><span class="technicaltitle">Memoria Interna</span> <br>32GB<br><br><span class="technicaltitle">Processore</span> <br>Processore Kirin 955 - Octa-Core (4x2,5 GHz + 4x1,8 GHz)<br><br><span class="technicaltitle">In dotazione</span> <br>Smartphone Auricolari stereo - Caricabatteria Cavo USB Type-C - Estrattore SIM Guida rapida<br><br><span class="technicaltitle">Dimensioni</span> <br>145 x 70,9 x 6,95 mm<br><br><span class="technicaltitle">Peso</span> <br>144 grammi<br><br><span class="technicaltitle">Autonomia</span> <br>Stand-by fino a 566 ore - Conversazione fino a 1980 min'),
(5, 'LG K8', 179.99, '3', 'Caratteristiche:<br>\n4G LTE - NFC<br>\nSistema Operativo Android 6<br>\nDisplay 5”<br>\nProcessore QuadCore 1.3 GHz', 'smartphones', 'LG', 'Android', './Immagini_Progetto/LG_k8.png', 'no', 'Specifiche tecniche<br>\r\n4G LTE - NFC\r\nSistema Operativo Android 6\r\nDisplay 5”\r\nProcessore QuadCore 1.3 GHz\r\nTecnologia\r\n4G cat.4/HSDPA42/UMTS/EDGE/GPRS Frequenze 850/900/1800/1900/2100<br>\r\nConnettivita\r\nWi-Fi - Bluetooth - Micro USB - NFC<br>\r\nGPS\r\nIntegrato<br>\r\nDisplay\r\n5” 16 Milioni colori Touch<br>\r\nFotocamera\r\nPosteriore da 8 Mpxl con flash<br>\r\nMemoria Interna\r\n8GB con Slot Memory Card Micro SD fino a 32GB<br>\r\nProcessore\r\nProcessore QuadCore 1.3 GHz<br>\r\nFormato SIM\r\nNano-sim<br>\r\nAudio e Video\r\nVideo Recorder&Playback - MP3 Player - Radio FM<br>\r\nIn dotazione\r\nCaricabatteria, Cavo dati USB, Manuale d’uso rapido, Auricolare stereo<br>\r\nDimensioni\r\n144,6x71,5x8,7 mm<br>\r\nPeso\r\n142 gr.<br><br>\r\nAutonomia(*)\r\nStand-by fino a 100 ore - Conversazione fino a 240 min.'),
(6, 'LG X screen', 269.99, '4', 'Caratteristiche:<br>\n4G LTE - NFC<br>\nSistema Operativo Android 6.0<br>\nDisplay 4.93” + Display secondario 1.76”<br>\nProcessore Snapdragon™ 410 QuadCore 1.2 GHz', 'smartphones', 'LG', 'Android', './Immagini_Progetto/blocchetto-lg-xsceen-black.png', 'no', 'Specifiche tecniche\n<br><br>\n4G LTE - NFC\n<br>Sistema Operativo Android 6.0\n<br>Display 4.93” + Display secondario 1.76”\n<br>Processore Snapdragon™ 410 QuadCore 1.2 GHz\n<br><br>Tecnologia\n4G cat.4/HSDPA42/UMTS/EDGE/GPRS Frequenze 850/900/1800/1900/2100\n<br><br>\nConnettivita\n<br>Wi-Fi - Bluetooth - Micro USB - NFC\n<br><br>\nGPS\n<br>Integrato\n<br><br>\nDisplay: Display 4.93” + Display secondario 1.76”\n<br><br>\nFotocamera Posteriore da 13 Mpxl con flash e Frontale da 5 Mpx\n<br><br>\nMemoria Interna\n<br>16GB\n<br>Slot Memory Card Micro SD fino a 32GB\n<br><br>\nProcessore: Snapdragon™ 410 QuadCore 1.2 GHz\n<br><br>\nFormato SIM: Nano-sim\n<br><br>\nAudio e Video\n<br>Video Recorder&Playback - MP3 Player - Radio FM\n<br><br>In dotazione:\n<br>Caricabatteria, <br>Cavo dati USB, <br>Manuale d’uso rapido,<br>Auricolare stereo\n<br><br>\nDimensioni: 142,6x71,8x7,1 mm\n<br><br>\nPeso: 120 gr.\n<br><br>\nAutonomia(*)\n<br>Stand-by fino a 100 ore<br>- Conversazione fino a 240 min.\n<br><br>\n* Le prestazioni delle batterie dipendono da vari fattori tra cui la vicinanza delle antenne, lo stato delle batterie, la posizione geografica e il tipo di rete utilizzata.'),
(7, 'Apple iPad Pro 9.7" 256 GB', 1199.99, '6', 'Caratteristiche:<br>\r\nDisplay Retina da 9,7" (diagonale) con True Tone e rivestimento antiriflesso<br>\r\nChip A9 con architettura a 64 bit di livello desktop<br>\r\nSensore di impronte digitali Touch ID<br>\r\nFotocamera iSight da 12MP con video a 4K<br>\r\nVideocamera FaceTime HD (foto da 5MP)<br>', 'tablet', 'Apple', 'iOS', './Immagini_Progetto/Tablet.jpg', 'no', 'Sistema Operativo iOS 9<br>\nDisplay Retina da 9,7” (diagonale) con True Tone e rivestimento antiriflesso<br>\nChip A9X di terza generazione con architettura a 64 bit di livello desktop<br>\nSensore di impronte digitali Touch ID<br>\nFotocamera iSight da 12MP con video a 4K<br>\nDisplay\nRetina Display 9,7” (diagonale) con True Tone e rivestimento antiriflesso<br>\n<br>\nSensori<br>\nimpronte digitali Touch ID<br>\n<br>\nProcessore<br>\nChip A9X di terza generazione con architettura a 64 bit di livello desktop<br>\n<br>\nFotocamera<br>\niSight da 12MP con video a 4K<br>\n<br>\nVideocamera<br>\nFaceTime HD (foto da 5MP)<br>\n<br>\nConnettivita<br>\n4G LTE Advanced1, Wi-Fi 802.11ac con tecnologia MIMO<br>\n<br>\nBatteria<br>\nFino a 10 ore di autonomia<br>\n<br>\nNote<br>\n1-Richiede un piano dati. La tecnologia 4G LTE è supportata solo in alcuni Paesi e solo da alcuni operatori. La velocità varia a seconda delle condizioni ambientali.<br>\n2-La durata della batteria varia a seconda dell’uso e della configurazione.'),
(8, 'Samsung Galaxy TAB A 9.7', 299.99, '4', 'Caratteristiche:<br>\r\nSistema Operativo Android 5.0<br>\r\nDisplay 9.7” TFT<br>\r\nProcessore Snapdragon™ 410 QuadCore 1.2 GHz<br>', 'tablet', 'Samsung', 'Android', './Immagini_Progetto/samsung-galaxy-tab-a-97-2.jpg', 'no', 'Design sottile e moderno<br>\r\n<br>\r\nLo stile essenziale e la cornice metallizzata esaltano il nuovo formato 4:3, donando a Galaxy TAB A un look moderno e sofisticato, garantendo la massima maneggevolezza grazie ai 7,5 millimetri di spessore e solo 456 grammi di peso.<br>\r\nEsperienza visiva ottimizzata<br>\r\n<br>\r\nProgettato per essere il tablet più portatile della categoria, Galaxy TAB A non accetta compromessi, regalandoti uno schermo più ampio rispetto ad altri tablet. Un nuovo display, ideale per visualizzare in modo ottimale presentazioni, siti web, pubblicazioni, e-book ed e-mail.<br>\r\nFoto perfette con Auto Focus<br>\r\n<br>\r\nLa fotocamera da 5 MP con messa a fuoco automatica permette di ottenere immagini sempre chiare e definite con la massima semplicità e in qualsiasi condizione. È anche possibile eseguire facilmente scansioni di codici QR e codici a barre migliorando l''interazione con il mondo che ti circonda.<br>\r\nInteressanti contenuti e servizi gratuiti<br>\r\n<br>\r\nL''esperienza di GALAXY TAB A è arricchita dai numerosi contenuti disponbili per te. Potrai leggere le tue riviste preferite grazie ai 6 mesi inclusi con MagBox e goderti un fantasitico e-book al mese per un anno con Kindle for Samsung.<br>\r\nPrestazioni eccellenti<br>\r\n<br>\r\nGrazie al processore Quad Core da 1.2GHz, 2GB di RAM, alla versione più recente di Android Lollipop e alla funzione Multischermo, è il dispositivo perfetto per chi prova per la prima volta un Tablet e per chi cerca un prodotto performante.<br>\r\nContenuti divertenti e protetti per i più piccoli<br>\r\n<br>\r\nCon la Modalità Bambino i più piccoli possono usare Galaxy Tab A che ha una loro area dedicata. Questa modalità prevede un’interfaccia divertente e protetta.<br>\r\nScatto continuo<br>\r\n<br>\r\nGrazie alla funzione Scatto Continuo potrete catturare rapidamente una serie successiva di scatti per immortalare ogni momento in rapida successione senza perdere nemmeno un secondo. Lo Scatto Continuo può essere attivato semplicemente tenendo premuta l''icona di scatto.<br>\r\nConnessione senza problemi<br>\r\n<br>\r\nLa Connessione Rapida* e Bluetooth tra SmartTV e TAB A controlla il TV dal Tablet, condivide i contenuti, e trasforma il tablet in un secondo display TV.*Funzione disponibile solo con i prodotti Tizen TV con Bluetooth in vendita dal 2015 o successivi.<br>'),
(9, 'Huawei MediaPad 10 LINK+', 199.99, '3', 'Caratteristiche:<br>\r\nDisplay 10.1” (1280x800) IPS 16M di colori<br>\r\nSistema Operativo Android™ 4.2.2 JB<br>', 'tablet', 'Huawei', 'Android', './Immagini_Progetto/huawei-mediapad-10-link-plus-1.jpg', 'no', 'HUAWEI MediaPad 10 Link+ è un tablet da 10,1 pollici con microprocessore quad-core HiSilicon Kirin 910 e supporto per le reti mobili 3G.<br>\r\n<br>\r\nCon un design unibody ultra-sottile di 9,9 millimetri in lega di alluminio, è elegante e portatile. MediaPad 10 Link+ ha uno schermo IPS HD con risoluzione di 1280×800 pixel.<br>\r\n<br>\r\nMonta una fotocamera frontale da 0,3 megapixel e una fotocamera posteriore da 3 megapixel. L''ottimo display in combinazione con la tecnologia audio DTS del MediaPad 10 Link+ offre una superba qualità audiovisiva, sia che si voglia scattare foto, giocare, guardare film in HD, o ascoltare musica<br>\r\n<br>\r\nDisplay 10.1” (1280x800) IPS 16M di colori<br>\r\nSistema Operativo Android™ 4.2.2 JB\r\nConnettivita<br>\r\nHSDPA+ 42.2Mbps/HSUPA 5.76/, Wi-Fi 802.11b/g/n, Bluetooth 3.0<br>\r\n<br>\r\nDisplay<br>\r\n10.1" (1280x800) IPS 16M di colori<br>\r\n<br>\r\nVideo/Audio/Picture<br>\r\n2 Fotocamera da 3 Mpx e VGA Lettore multimediale - MP3, WAV, 3GP, AAC, AAC+ e-AAC+, JPG, PNG,GIF, BMP, WMV, H264, Mpeg4, 1080p/30fps<br>\r\n<br>\r\nMemoria<br>\r\n8GB (espandibile fino a 32GB)<br>\r\n<br>\r\nProcessore<br>\r\nBalon Cortex A9 Quad-Core 1.6GHz<br>\r\n<br>\r\nSistemaOperativo<br>\r\nAndroidTM 4.2.2 Jelly Bean<br>\r\n<br>\r\nApplicazioni<br>\r\nGoogle Mobile Services, Youtube, E-mail, GPS e A-GPS, SMS, Invio e ricezione, chiamata voce.<br>\r\n<br>\r\nIn dotazione<br>\r\nCaricabatteria - Manuale d’uso<br>\r\n<br>\r\nDimensioni<br>\r\n257.4x175.9x9.9mm<br>\r\n<br>\r\nPeso<br>\r\n630 grammi<br>\r\n<br>\r\nAutonomia (*)<br>\r\nStand-by fino a 600h<br>\r\n<br>\r\nNote<br>\r\n1 - Le prestazioni delle batterie dipendono da vari fattori tra cui la vicinanza delle antenne, lo stato delle batterie, la posizione geografica e il tipo di rete utilizzata.<br>'),
(10, 'Samsung Galaxy View 18.4"', 799.9, '1', 'Caratteristiche:<br>\r\nProcessore OctaCore 1.6 GHz<br>\r\nDisplay 18.4” TFT, 1920x1080 Full HD<br>\r\nSistema Operativo AndroidTM 5.1 (Lollipop)<br>\r\nMemoria interna 32GB (espandibile fino a 128GB)<br>\r\nInternet TV<br>', 'tablet', 'Samsung', 'Android', './Immagini_Progetto/blocchetto-galaxy-view-timvision.png', 'yes', 'Display 18.4” TFT PLS ,1920x1080 Full HD<br>\r\nSistema Operativo AndroidTM 5.1 (Lollipop)<br>\r\nMemoria Interna 32GB (espandibile fino a 128GB)<br>\r\nInternet TV<br>\r\n<br>\r\nConnettivita<br>\r\nConnettività WirelessBluetooth 4.1, BLEWi-Fi 802.11 a/b/g/n/ac<br>\r\n<br>\r\nDisplay<br>\r\nDisplay 18.4” TFT PLS ,1920x1080 Full HD<br>\r\n<br>\r\nDimensioni<br>\r\n451,8x275,8x11,9 mm.<br>\r\n<br>\r\nPeso<br>\r\n2,65 kg<br>\r\n<br>\r\nFotocamera<br>\r\nFotocamera (Front: 2.1 MP)<br>\r\n<br>\r\nFormati supportati<br>\r\nLettore multimediale, aac,amr,awb,mp3,ogg,wav, DivX, XviD, MPEG4, VP8, H.263, H.264, H.265<br>\r\n<br>\r\nMemoria<br>\r\nInterna 32GB (espandibile fino a 128GB)<br>\r\n<br>\r\nProcessore<br>\r\nOctaCore da 1.6 GHzx<br>\r\n<br>\r\nSistema Operativo<br>\r\nAndroidTM 5.1 (Lollipop)<br>\r\n<br>\r\nIn confezione<br>\r\nCarica batteria, Manuale d’uso<br>\r\n<br>\r\nApplicazioni<br>\r\nAndroid Market, Google Mobile App, Youtube, Inserimento testo e ricerca vocale, E-mail, GPS Glonass, SMS/MMS<br>\r\n<br>\r\nAutonomia<br>\r\nfino a 8h in video play<br>\r\n<br>\r\nNote<br>\r\n1 - Le prestazioni delle batterie dipendono da vari fattori tra cui la vicinanza delle antenne, lo stato delle batterie, la posizione geografica e il tipo di rete utilizzata.<br>'),
(11, 'Apple iPad Air 2', 509.9, '1', 'Caratteristiche:<br>\r\nWi-Fi + Cellular (4G LTE)<br>\r\nDisplay Retina da 9,7" (diagonale)<br>\r\nSistema Operativo iOS 8 (Processore A8X)<br>\r\nFotocamera iSight da 8 megapixel<br>', 'tablet', 'Apple', 'iOS', './Immagini_Progetto/blocchetto_ipad-air-2-silver-1.jpg', 'no', 'L’iPad Air più sottile di sempre è anche il più potente e versatile. È un concentrato di tecnologie evolute, a cominciare dal sensore di impronte digitali Touch ID.<br>\r\n<br>\r\nSistema Operativo iOS 8<br>\r\nDisplay Retina da 9,7" (diagonale)<br>\r\nChip A8X<br>\r\nFotocamera iSight da 8 megapixel<br>\r\nDisplay<br>\r\nRetina da 9,7" (diagonale)<br>\r\n<br>\r\nSensori<br>\r\nimpronte digitali Touch ID<br>\r\n<br>\r\nProcessore<br>\r\nChip A8X<br>\r\n<br>\r\nFotocamera<br>\r\niSight da 8MP<br>\r\n<br>\r\nVideocamera<br>\r\nFaceTime HD<br>\r\n<br>\r\nConnettivita<br>\r\nWi-Fi 802.11ac con tecnologia MIMO + Cellular - 4G LTE più veloce<br>\r\n<br>\r\nBatteria<br>\r\nFino a 10 ore di autonomia<br>\r\n<br>\r\nNote<br>\r\n1 - La durata della batteria varia a seconda dell’uso e della configurazione.<br>\r\n2 - Richiede un piano dati. La tecnologia 4G LTE è supportata solo in alcuni Paesi e solo da alcuni operatori. La velocità varia a seconda delle condizioni ambientali.'),
(12, 'Acer ICONIA W4 821', 299.99, '4', 'Caratteristiche:<br>\r\nDisplay 8” (1280x800) IPS<br>\r\nSistema Operativo Windows 8.1 + Office Home & Students 2013<br>', 'tablet', 'Acer', 'Windows', './Immagini_Progetto/blocchetto_acer-iconia-w4-grigio-1.jpg', 'no', 'Display 8” (1280x800) IPS<br>\r\nSistema Operativo Windows 8.1 + Office Home & Students 2013<br>\r\n<br>\r\nConnettivita<br>\r\nHSDPA 21.2/HSUPA 5,76/,Wi-Fi Direct 802.11 a/b/g/n, Bluetooth 4.0 - Chiamata voce<br>\r\n<br>\r\nDisplay<br>\r\n8" (1280x800) IPS<br>\r\n<br>\r\nVideo/Audio/Picture<br>\r\n5 Mpx A/F + 2 Mpx frontale, Lettore multimediale, MP3, WAV, 3GP, AAC, AAC+, e-AAC+, JPG, PNG,GIF, BMP, WMV, DivX/AVI<br>\r\n<br>\r\nMemoria<br>\r\n32GB, 2GB RAM<br>\r\n<br>\r\nProcessore<br>\r\nIntel Atom Quad-Core 1.8GHz<br>\r\n<br>\r\nSistemaOperativo<br>\r\nWindows 8.1 + Office Home & Students 2013<br>\r\n<br>\r\nApplicazioni<br>\r\nOffice Home & Students 2013, E-mail, GPS/A-GPS, SMS/MMS Invio e ricezione<br>\r\n<br>\r\nIn dotazione<br>\r\nCaricabatteria - Guida di riferimento rapido<br>\r\n<br>\r\nDimensioni<br>\r\n218.9 x 134.9 x 10.75 mm<br>\r\n<br>\r\nPeso<br>\r\n420 grammi<br>\r\n<br>\r\nAutonomia (*)<br>\r\n4960 mAh / durata 8h<br>\r\n<br>\r\nNote<br>\r\n1 - Le prestazioni delle batterie dipendono da vari fattori tra cui la vicinanza delle antenne, lo stato delle batterie, la posizione geografica e il tipo di rete utilizzata.<br>'),
(13, 'TIM Modem Fibra', 8.25, '1', 'Caratteristiche:<br>\nCollegamento a PC, tablet, telefoni<br>\nNavigazione senza fili<br>\nBanda Wi-Fi a 2.4 Ghz e 5 Ghz<br>\nControllo e gestione con l’App 187<br>', 'modem', 'TIM', NULL, './Immagini_Progetto/prodotti_modem_fibra_tim_01.jpg', 'no', '<br>Collegamento a PC, tablet, telefoni\n<br>Navigazione senza fili\n<br>Banda Wi-Fi a 2.4 Ghz e 5 Ghz\n<br>Controllo e gestione con l’App 187\n<br>Tecnologia\nADSL/ADSL 2+/VDSL\n<br><br>\nWi-Fi\n<br>802.11 b/g/n a 2.4 Ghz e 5 Ghz simultanee\n<br><br>\nInterfacce\n<br>- 1 porta ADSL/VDSL<br>- 1 porta WAN 4 porte Gigabit Ethernet<br>- 1 Interfaccia Dect integrata<br>- 1 porta PSTN<br>- 2 porte FXS per collegamento di telefoni<br>- 2 porte USB per collegamento dischi e stampanti\n<br><br>\nFunzioni avanzate\n<br>Condivisione foto, musica e video, Hard Disk e stampanti\n<br><br>\nRequisiti tecnici\n<br>Linea ADSL Flat o Fibra Ottica di Telecom Italia\n<br><br>\nRequisiti di sistema per la gestione dell’interfaccia modem da PC\n<br>Principali browser inseriti di default sui sistemi operativi Windows 8, Windows 7, Vista, XP - MacOS 10.3\n<br><br>\nAssistenza tecnica\n2 anni di garanzia sul prodotto\n<br><br>\nContenuto della confezione:<br>\nModem Fibra,<br>filtro DSL con 2 cavi telefonici già collegati,<br>cavo Ethernet con connettori gialli,<br>alimentatore'),
(14, 'Technicolor Wi-Fi Bridge', 79.99, '1', 'Caratteristiche:\n<br>Design verticale compatto\n<br>Wi-Fi AC 4x4 ad altissime prestazioni\n<br>Associazione al modem in modalità WPS\n<br>Due porte Gigabit Ethernet\nLed di stato', 'modem', 'Technicolor', NULL, './Immagini_Progetto/blocchetto-wifi-bridge-techniclor.png', 'no', 'Specifiche tecniche\n<br><br>\nDesign verticale compatto\n<br>Wi-Fi AC 4x4 ad altissime prestazioni\n<br>Associazione al modem in modalità WPS\n<br>Due porte Gigabit Ethernet\n<br>Led di stato\n<br>Tecnologia Wi-Fi IEEE 802.11ac 5 GHz 4x4\n<br><br>\nInterfacce\n<br>2 Porte Ethernet\n<br><br>\nContenuto della confezione:\n<br>Multimedia Connect; <br>Alimentatore;<br>Cavo Ethernet;<br>Guida rapida; <br>Garanzia di conformità; <br>Foglio di sicurezza'),
(15, 'AVM FRITZ!WLAN Repeater 1750E', 50, '1', 'Caratteristiche:\n<br>Estende la portata wireless fino a 1750 Mbit/s\n<br>WPS: lo installi premendo un pulsante\n<br>Compatibile con i modem Wi-Fi di TIM\n<br>Porta LAN Gigabit\n5 anni di garanzia', 'modem', 'AVM', NULL, './Immagini_Progetto/blocchetto-repeater-fritz-1750e.png', 'yes', 'Caratteristiche\n<br><br>\nSupporto reti Wi-Fi, fino a 1750 Mbps a 2.4 e 5 GHz (dual band, simultanee)\n<br>Compatibile con tutti i modem Wi-Fi (anche mobile)\n<br>Facile da installare con WPS, sicuro grazie alla codifica WPA2\n<br>Porta LAN Gigabit, modalità Repeater o Access Point\n<br>5 anni di garanzia\n<br>Standard Wi-Fi e velocità 802.11ac (1.300 Mbit/s), 802.11n (450 Mbit/s), 802.11g/a (54 Mbit/s) e 802.11b (11 Mbit/s)\n<br><br>\nSicurezza Wi-Fi\n<br>WPA2, WPA, WPS\n<br><br>\nCaratteristiche operative:\n<br>Assistente per browser e software per semplificare la configurazione\n<br><br>\nDimensioni\n<br>(L x H x P): circa 76,5 x 155 x 62,6 mm\n<br><br>\nPeso\n<br>151 g circa\n<br><br>\nContenuto della confezione\nWireless Range Extender,Cavo Ethernet,Guida rapida'),
(16, 'TIM Modem ADSL Wi-Fi', 69, '1', 'Caratteristiche:<br>\nNavigazione senza fili più veloce\n<br>Connessione di vari dispositivi\n<br>Installazione no problem\n<br>Funzione Eco per risparmio energetico', 'modem', 'TIM', NULL, './Immagini_Progetto/blocchetto-modem-adsl-new.png', 'no', 'Specifiche tecniche\n<br><br>\nNavigazione senza fili più veloce\n<br>Connessione di vari dispositivi\n<br>Installazione no problem\n<br>Funzione Eco per risparmio energetico\n<br><br>Tecnologia\n<br>ADSL/ADSL2+; velocità fino a 20 Mbps down/1 Mbps up\n<br><br>\nWi-Fi\n<br>Wi-Fi 802.11 b/g/n; velocità di trasferimento fino a 300Mbps\n<br><br>\nInterfacce\n<br>Interfacce USB alta velocità (480 Mbit/s) ad alta potenza (500 mA), 1 porta connettore tipo A Interfaccia Wi-FiStandard IEEE 802.11nInterfaccia radio 2.4Ghz, 2 antenne, velocità di trasmissione teorica 300 Mbps\n<br><br>\nProtezione Wireless\n<br>WPA, WPA-PSK, WEP - Supporto Wi-Fi Protected Setup - Controllo di accesso\n<br><br>\nFunzioni avanzate\n<br>Funzionalità di routing avanzate (DHCP server, NAT, NAPT, Virtual Server) - Firewall - Condivisione Hard Disk e Stampante USB\n<br><br>\nAssistenza tecnica\n<br>2 anni di garanzia sul prodotto\n<br><br>\nContenuto della confezione\n<br>Guida di installazione; CD autoinstallante (compatibile con Windows 7, Vista, XP- MacOS 10.3); 1 filtro ADSL 2+; 1 cavo Telefonico; 1 cavo Ethernet'),
(17, 'ZyXEL Repeater Wi-Fi AC750', 49.99, '1', 'Caratteristiche:\n<br>Funzionamento simultaneo a 2.4 e 5 GHz\n<br>Velocità di trasmissione fino a 750 Mbps\n<br>Compatibilità Wi-Fi b/g/n a 2.4 GHz e Wi-Fi n/ac a 5 GHz\n<br>Associazione al modem in modalità WPS', 'modem', 'ZyXEL', NULL, './Immagini_Progetto/blocchetto-repeater-zyxel-ac750.png', 'no', 'Caratteristiche tecniche\n<br><br>\nFunzionamento simultaneo a 2.4 e 5 GHz\n<br>Velocità di trasmissione fino a 750 Mbps\n<br>Compatibilità Wi-Fi b/g/n a 2.4 GHz e Wi-Fi n/ac a 5 GHz\n<br>Associazione al modem in modalità WPS\n<br>Standard Wi-Fi 802.11 a / b / g / n / ac\n<br><br>\nVelocità Wi-Fi:<br>300 Mbps * (2,4 GHz),<br>450 Mbps * (5 GHz)<br>Ricezione:<br>300 Mbps * (2,4 GHz),<br>450 Mbps * (5 GHz)\n<br><br>\nSicurezza Wi-Fi\n<br>64/128 bit WEP, WPA / WPA2, WPA-PSK / WPA2-PSK\n<br><br>\nCaratteristiche operative:\n<br>Modalità Ripetitore,<br>Modalità AP,<br>Wi-Fi Protected Setup (WPS),<br>Wi-Fi Multimedia (WMM),<br>Selezione automatica dei canali,<br>Programmazione senza fili,<br>Gestione di potenza di uscita senza fili,<br>Filtraggio degli indirizzi MAC,<br>Modalità di impostazione di copertura.\n<br><br>\nSoftware\n<br>Aggiornamento del firmware online\n<br><br>\nSpecifiche hardware\n<br>LAN: 10/100 Mbps One Ethernet RJ-45 porta con auto MDI / MDIX supporto\n<br><br>\nDimensioni\n<br>(LxPxA): 46,5 x 62,3 x 90,9 mm\n<br><br>\nPeso: 98 g\n<br><br>\nAmbiente operativo\n<br>Temperatura: 0 ° C a 40 ° C (32 ° F a 104 ° F) Umidità: 10% a 90% (senza condensa)\n<br><br>\nContenuto della confezione\n<br>Wireless Range Extender,\n<br>Cavo Ethernet,\n<br>Guida rapida,\n<br>Certificato di garanzia,\n<br>CD di supporto'),
(18, 'ZyXEL Repeater ZyXEL N300', 39, '1', 'Wi-Fi fino a 300 Mbps a 2.4 GHz<br>\r\nPer qualsiasi rete 802.11b/g/n<br>\r\nAggiornamento firmware online<br>\r\nSi installa premendo un pulsante', 'modem', 'ZyXEL', NULL, './Immagini_Progetto/prodotti_blocchetto_repeater_zyxel_n300.png', 'no', 'Tecnologia<br>\r\nWi-Fi b/g/n a 2.4 GHz<br><br>\r\n\r\nVelocità di trasmissione<br>\r\nfino a 300 Mbps<br><br>\r\n\r\nConnettivita<br>\r\nAssociazione al modem ADSL in modalità WPS<br><br>\r\n\r\nLED<br>\r\nIndicatore di intensità del segnale trasmissivo tra repeater e modem ADSL<br><br>\r\n\r\nPorta per collegamenti via cavo<br>\r\nEthernet<br><br>\r\n\r\nCopertura wireless<br>\r\nFacile estensione per qualsiasi rete 802.11b/g/n<br><br>\r\n\r\nServizi<br>\r\nAggiornamento firmware online<br><br>\r\n\r\nIn dotazione<br>\r\nRepeater, Cavo Ethernet, Guida rapida di installazione'),
(19, 'TIM TIMTag', 129, '3', 'Caratteristiche:\r\nResistente all’acqua\r\nFornisce allarmi di movimento (velocità, inerzia, crash)\r\nBatteria di lunga durata\r\nDimensioni 49 x 47 x 17 mm', 'tv', 'TIM', NULL, './Immagini_Progetto/timtag-newlogo-blocchetto.png', 'no', 'TIMTag è:\r\n\r\n	\r\nResistente all’acqua\r\n\r\n	\r\nFornisce allarmi di movimento (velocità, inerzia, crash)\r\n\r\n	\r\nHa una batteria di lunga durata\r\n\r\n	\r\nFornisce allarmi per uscita da zone sicure (geofence)'),
(20, 'D-Link Smart Home', 5, '1', 'Con lo Smart Home HD Starter Kit potrai impostare, controllare, monitorare e automatizzare la tua casa ovunque ti trovi.<br>\r\nNel Kit sono inclusi:<br>\r\n<br>\r\nUn Monitor HD (DCS-935L) <br>\r\nUn Wi-Fi Motion Sensor (DCH-S150)<br>\r\nUna smart plug (DSP-W215) <br>\r\nTramite l''App mydlink Home per smartphone e tablet hai a disposizione il controllo di tutti i dispositivi così da semplificarti la gestione della casa rendendola più sicura e intelligente.\r\n', 'tv', 'D-Link', NULL, './Immagini_Progetto/DLinkHD_0.jpg', 'no', 'Servizio gratuito<br>\r\nVisualizzazione da smartphone o tablet delle riprese<br>\r\nInvio notifiche su smartphone/tablet/e-mail<br>\r\nConnettività Wi-Fi tramite ADSL o modem mobile 3G o 4G'),
(21, 'D-Link 5010L', 99.99, '2', 'Tecnologia wireless N<br>\r\nLED a infrarossi integrati<br>\r\nAccesso tramite Internet<br>\r\nVideo VGA 480p', 'tv', 'D-Link', NULL, './Immagini_Progetto/blocchetto-ipcam-motorizzata.png', 'no', 'Capacità Pan/Tilt\r\n360/120 gradi\r\n\r\nDesign\r\ncompatto\r\n\r\nMemoria\r\nSlot per scheda MicroSD (non inclusa) per storage di registrazioni audio e video\r\n\r\nRegistrazione\r\nVideo in definizione VGA (480p) e immagini compresse in H.264\r\n\r\nConnettivita\r\nTecnologia Wireless N - Pulsante Wireless security con Wi-Fi Protected Setup (WPS)\r\n\r\nLED\r\nLED InfraRossi per vision notturna fino a 8m\r\n\r\nSensori<br>\r\nSensore PIR (Passive Infrared) per rilevazione movimenti<br>\r\n<br>\r\nAvanzate<br>\r\nInvio di e-mail in caso di movimento rilevato<br>\r\n<br>\r\nMicrofono<br>\r\nMicrofono integrato<br>\r\n<br>\r\nCloud<br>\r\nmydlink™ Cloud Services: il modo più semplice e veloce per monitorare da remoto'),
(22, 'TIM Pack TIMvision&Chromecast', 39, '1', 'Con Chromecast porti TIMvision sulla tua TV<br>\r\nIl tuo smarthphone come un telecomando<br>\r\nPlug and play<br>\r\nTrasmetti qualsiasi contenuto dal tuo telefono \r\nAndroid o dal browser Chrome<br>\r\nVideo in alta definizione', 'tv', 'TIM', NULL, './Immagini_Progetto/CHROMECAST-1.jpg', 'no', 'Dimensioni\r\nDispositivo: 51,9 x 51,9 x 13,49 mm\r\nConfezione: 124,4 mm x 42,85 mm x 124 mm\r\nCavo di alimentazione: 1,75 m\r\n\r\nPeso\r\n39,1g\r\n\r\nPorte e connettori\r\nHDMI compatibile CEC (Consumer Eletronic Control)\r\nMicro USB\r\n\r\nColore\r\nNero\r\n\r\nRisoluzione\r\n1080p\r\n\r\nConnettivita<br>\r\nWi-Fi 802.11 b/g/n/ac (2,4 GHz/5 GHz)<br><br>\r\n\r\nSicurezza<br>\r\nWEP, WPA/WPA2<br><br>\r\n\r\nAlimentazione<br>\r\nAlimentazione 5V, 1A<br><br>\r\n\r\nSistema Operativo Supportato<br>\r\nAndroid 4.1 e versioni successive\r\niOS 7.0 e versioni successive\r\nWindows 7 e versioni successive\r\nMac OS X 10.7 e versioni successive\r\nChrome OS'),
(23, 'Nokia Cassa MD 12', 49.99, '1', 'Speaker bluetooth Nokia MD-12 colore bianco. NFC. Ascoltare la tua musica preferita è ora più semplice chemai. Con il suo design ultra - compatto ed una vasta gamma di bellissimi colori , MD -12 è abbastanza piccoloda stare in tasca. Grande esperienza bassi. Non lasciate che la sua piccola dimensione vi inganni . Questopiccolo altoparlante dispone di un grande carico di energia . Progettato con le ultime tecnologie , MD -12 èstato progettato con un attuatore integrato, creando un grande effetto dei bassi quando è impostato su quasiqualsiasi superficie . La durata della batteria superiore per un più divertente ascolto. Con NFC incluso , bastatoccare il tuo telefono cellulare abilitato NFC al diffusore e siete a posto. Oppure utilizzare il Bluetooth edascoltate in streaming i propri brani in modalità wireless e ballate tutta la notte con 15 ore di riproduzionemusicale garantite.', 'tv', 'Nokia', NULL, './Immagini_Progetto/Nokia-md-12_orange_230x230.png', 'no', 'Numero altoparlanti frontali centrali<br>\r\n0<br><br>\r\n\r\nNumero altoparlanti frontali laterali<br>\r\n1<br><br>\r\n\r\nNumero altoparlanti retro<br>\r\n0<br><br>\r\n\r\nSubwoofer<br>\r\nNo<br><br>\r\n\r\nPortatile<br>\r\nSi<br><br>\r\n\r\nTipologia di utilizzo<br>\r\nDiffusore da interno/esterno<br><br>\r\n\r\nColore primario<br>\r\nBianco<br><br>\r\n\r\nConsumo<br>\r\n0W<br><br>\r\n\r\nWireless altoparlanti frontali laterali<br>\r\nSi<br><br>\r\n\r\nPotenza altoparlanti frontali laterali<br>\r\n0W<br><br>\r\n\r\nMateriale altoparlanti frontali laterali<br>\r\nPlastica<br><br>\r\n\r\nDiametro Bass altoparlanti frontali laterali<br>\r\n0 mm<br><br>\r\n\r\nWireless Subwoofer<br>\r\nNo<br><br>\r\n\r\nPotenza Subwoofer<br>\r\n0W<br><br>\r\n\r\nMateriale Subwoofer<br>\r\nPlastica<br><br>\r\n\r\nDiametro Bass<br>\r\n0 mm'),
(24, 'Samsung Smart TV 50" + Soundbar con TIMvision', 26.08, '1', 'Modello 50JU6400 - 50“<br>\r\nUltra HD - 4K 3840 x 2160<br>\r\nSoundbar HW-J250 inclusa<br>\r\nTIMvision incluso', 'tv', 'Samsung', NULL, './Immagini_Progetto/samsung_smart_tv_50JU6400_blocchetto.png', 'yes', 'Modello 50JU6400 - 50“<br>\r\nUltra HD - 4K 3840 x 2160<br>\r\nSoundbar HW-J250 inclusa<br>\r\nTIMvision incluso'),
(25, 'Samsung Galaxy Gear S', 349.9, '4', 'Caratteristiche:<br>\r\nOrologio Multifunzione Intelligente<br>\r\nDisplay 2” curved SuperAMOLED<br>\r\nProcessore DualCore 1GHz<br>\r\nCertificazione IP67<br>', 'tv', 'samsung', NULL, './Immagini_Progetto/i1.jpg', NULL, 'Orologio Multifunzione Intelligente<br>\r\nDisplay 2” curved SuperAMOLED<br>\r\nProcessore DualCore 1GHz<br>\r\nCertificazione IP67<br>\r\n<br>\r\nConnettivita<br>\r\nHSDPA 21Mbps/UMTS/EDGE/GPRS - Wi-Fi - Bluetooth - **Micro USB<br>\r\n<br>\r\nFrequenze<br>\r\n2G: 900/1800 - 3G: 900/2100<br>\r\n<br>\r\nDisplay<br>\r\nTouch da 2”<br>\r\n<br>\r\nFormato SIM<br>\r\nNano<br>\r\n<br>\r\nMemoria interna<br>\r\n4GB*<br>\r\n<br>\r\nAltro<br>\r\nNotifiche, Chiamate, SMS, S Health,Lettore musicale, Meteo, Navigatore, Comandi vocali, Running\r\nDownload ulteriori applicazioni tramite il Samsung Gear Apps<br>\r\n<br>\r\nIn dotazione:<br>\r\n** Supporto per la carica Micro USB - Carica batteria - Guida di riferimento rapido<br>\r\n<br>\r\nDimensioni<br>\r\n39,9 x 58,1 x 12,5 mm<br>\r\n<br>\r\nPeso<br>\r\n84 gr.<br>\r\n<br>\r\nBatteria<br>\r\n300mAh<br>\r\n<br>\r\nNote<br>\r\n(*) Memoria interna: Parte della memoria interna indicata è utilizzata dal sistema operativo e dalle applicazioni preinstallate<br>'),
(26, 'Beats Solo2 On-Ear Headphones', 199.9, '3', 'Caratteristiche:<br>\r\nPeso 205 grammi<br>\r\nLarghezza 156 mm<br>\r\nCavo RemoteTalk™<br>', 'tv', 'beats', NULL, './Immagini_Progetto/beats-solo2-on-ear-red-1.jpg', NULL, 'Audio potenziato con la nuova qualità sonora Beats, il suono delle cuffie Solo2 è più nitido e più pulito e sprigiona una più vasta gamma di emozioni. Le cuffie Solo2 offrono un''ampia gamma di frequenze alte e bassi profondi per un''esperienza di ascolto equilibrata per tutti i generi musicali.<br>\r\n<br>\r\nVestibilità e stile: comfort, durevolezza e stile. Padiglioni curvati di 15 gradi per un comfort prolungato; la flessibilità rotazionale consente ai padiglioni di flettersi per una vestibilità ancor più personalizzata<br>\r\n<br>\r\nPeso 205 gr.<br>\r\nLarghezza 156 mm<br>\r\nCavo RemoteTalk™<br>\r\nDimensioni<br>\r\n156 mm (larghezza)<br>\r\n<br>\r\nPeso<br>\r\n205 gr.<br>\r\n<br>\r\nContenuto della confezione<br>\r\nCavo RemoteTalk™, Custodia da viaggi<br>');

-- --------------------------------------------------------

--
-- Struttura della tabella `sldevice`
--

CREATE TABLE IF NOT EXISTS `sldevice` (
  `deviceid` int(10) NOT NULL,
  `slid` int(10) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dump dei dati per la tabella `sldevice`
--

INSERT INTO `sldevice` (`deviceid`, `slid`) VALUES
(24, 2),
(10, 4),
(3, 3),
(19, 6),
(20, 8),
(25, 10),
(26, 3);

-- --------------------------------------------------------

--
-- Struttura della tabella `smartlife`
--

CREATE TABLE IF NOT EXISTS `smartlife` (
  `id` int(10) NOT NULL,
  `name` text COLLATE latin1_general_ci NOT NULL,
  `price` float NOT NULL,
  `description` longtext COLLATE latin1_general_ci,
  `category` enum('tv','health','home','personal') COLLATE latin1_general_ci NOT NULL,
  `img` text COLLATE latin1_general_ci NOT NULL,
  `promotion` enum('yes','no') COLLATE latin1_general_ci DEFAULT NULL,
  UNIQUE KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

--
-- Dump dei dati per la tabella `smartlife`
--

INSERT INTO `smartlife` (`id`, `name`, `price`, `description`, `category`, `img`, `promotion`) VALUES
(1, 'TIMvision', 5, 'Accomodati e goditi il grande cinema\r\n\r\nUna ricca proposta di film con le anteprime più attese, i grandi claassici, inediti, film d’azione, thriller, animazione e commedie per tutta la famiglia.In più l’HD, per rendere ogni immagine spettacolare e non perdere neanche un particolare', 'tv', './Immagini_Progetto/Schermata_2016-07-18_alle_17.57.51.png', 'yes'),
(2, 'Serie A TIM', 19.99, 'Serie A TIM\r\n\r\nVivi il meglio della Serie A TIM e i migliori momenti del Campionato 2015/2016 con tutte le notizie, i video-goal, le sintesi sul tuo Smartphone o Tablet e senza consumare GB. L’unica App ufficiale della Serie A TIM. Scarica l’App e vivi la magia del calcio!', 'tv', './Immagini_Progetto/Schermata_2016-07-18_alle_18.02.32.png', 'no'),
(3, 'TIMmusic', 7.99, 'LA COLONNA SONORA DELLA TUA VITA\r\n\r\nEntra in un mondo di musica con l''app TIMmusic. Milioni di brani in streaming, tutte le ultime uscite discografiche e tante playlist, da ascoltare dove e quando vuoi, senza consumare GB!\r\n', 'tv', './Immagini_Progetto/banner-2_1.jpg', 'yes'),
(4, 'TIMreading', 3.49, 'TIMreading\r\n\r\nPorta sempre con te su Smartphone e Tablet i tuoi eBook preferiti,\r\nascolta gli audiolibri dovunque tu sia, segui tutte le tue passioni scegliendo tra\r\ni magazine più amati e sfoglia il tuo quotidiano dalle prime ore del mattino.\r\nSu TIMreading trovi ciò che ami leggere e ascoltare, dove e quando vuoi.', 'tv', './Immagini_Progetto/tim-reading.jpg', 'no'),
(5, 'TIMgames', 1, 'TIMgames\r\n\r\nSparatutto, sport estremi, i migliori Classici e molto altro ancora... Con TIMgames hai a disposizione centinaia di giochi per il tuosmartphone e tablet, per divertirti dove e quando vuoi', 'tv', './Immagini_Progetto/tim-games.jpg', 'no'),
(6, 'TIM Tag', 12.99, 'TIMTag è il dispositivo che ti informa sulla posizione del tuo amico a quattro zampe e delle cose a te più care.\r\nSegui in tempo reale i suoi spostamenti sul tuo smartphone senza perderlo mai di vista.<br>Con TIMTag hai un dispositivo di localizzazione GPS di ultima generazione, con 12 mesi di servizio TIMTag e una TIM Card inclusi e un'' App dedicata intuitiva e semplice da utilizzare!', 'home', './Immagini_Progetto/TIM-Tag-Device-new-logo.jpg', 'yes'),
(7, 'TIM Home Connect', 1.5, 'TIM Home Connect è l’offerta pensata per essere utilizzata nei dispositivi di domotica presenti nella casa, la cui gestione prevede l''uso di una SIM.<br>Con Tim Home Connect infatti hai a disposizione minuti, MB e SMS da utilizzare per connettere e gestire il tuo antifurto, la tua caldaia o altri sistemi di domotica.<br>L''offerta prevede ogni 30 giorni:<br>20 minuti di chiamate<br>100 MB di traffico Internet<br>100 SMS verso tutti', 'home', './Immagini_Progetto/timcasa-zoom_2.png', 'no'),
(8, 'D-Link SmartHome', 5, '<b>Descrizione</b><br>Con lo Smart Home HD Starter Kit potrai impostare, controllare, monitorare e automatizzare la tua casa ovunque ti trovi.<br>Nel Kit sono inclusi:<br>Un Monitor HD (DCS-935L)<br>Un Wi-Fi Motion Sensor (DCH-S150)<br>Una smart plug (DSP-W215)<br>Tramite l''App mydlink Home per smartphone e tablet hai a disposizione il controllo di tutti i dispositivi così da semplificarti la gestione della casa rendendola più sicura e intelligente.<br>Facile configurazione e gestione dei tuoi dispositivi.<br>Basta semplicemente scaricare l’app mydlink Home e la configurazione guidata ti aiuterà a utilizzare al meglio tutti i dispositivi presenti nel kit in modo facile e intuitivo.<br>Con l’app potrai creare tu stesso le regole per accendere e spegnere i tuoi elettrodomestici quando e ovunque vuoi.', 'home', './Immagini_Progetto/dlink-smarthome.jpg', 'no'),
(9, 'Payments', 0, '<span color="#003d97">SICURO</span><br>\r\nI dati della tua carta di credito o prepagata sono memorizzati in modo confidenziale e protetto sulla TIM Card<br>\r\n<br>\r\n<span color="#003d97">SEMPLICE E VELOCE</span><br>\r\nBasta un tocco per scegliere la carta con cui effettuare i tuoi acquisti<br>\r\n<br>\r\n<span color="#003d97">COMODO</span><br>\r\nLasci il portafoglio a casa e utilizzi lo smartphone per avere a disposizione le tue carte', 'personal', './Immagini_Progetto/unnamed.png', NULL),
(10, 'Samsung Galaxy Gear S con SIM', 0, 'Un elegante display Super AMOLED curvo per una vestibilità ottimale, schermate personalizzabili e cinturini intercambiabili per esprimere al meglio il proprio stile.<br>\r\nTieniti in forma con questo fantastico prodotto e i servizi TIM.', 'health', './Immagini_Progetto/samsung-galaxy-gear-s-1_0.jpg', NULL);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
